### PR TITLE
Autoterminal: improved performance

### PR DESCRIPTION
**Pull request by basxto**

### CODE REVIEW

**Comment by basxto** [comment]
@Rainerd all checks passed

**Comment by basxto** [comment]
Okay, I will see that I’ll go through that code too, this weekend.
But it’s basically legit to throw out load_xbm_char. I wanted it to be reusable, but since the font bit array will not make it work with any other kind of font besides of xbm.

**Comment by basxto** [comment]
temporarely on hold

**Comment by vifino** [comment]
Uhm. You've messed up the branch, it now contains commits from master..

**Comment by basxto** [comment]
I merged master, but rebase remvoved the merge and made them own commits

**Pull request merged**
